'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not efib_resultceed four million, find the sum of the even-valued terms.

'''

def main():
	result = 0
	i = 2
	limit = 4000000
	limit_reached = False
	while not limit_reached:
		fib_result = fib(i)
		i += 1
		if fib_result > limit:
			limit_reached = True
		if fib_result % 2 == 0:
			result += fib_result
	return result

def fib(num):
	if num == 1:
		return 1
	if num == 2:
		return 2
	return fib(num - 2) + fib(num - 1)

if __name__ == '__main__':
	print(main())
