'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def main(limit):
	return sum(x for x in gen_fib(limit) if x % 2 == 0)

def gen_fib(limit):
	n1, n2 = 1, 2
	yield n1
	yield n2
	while n1 + n2 < limit:
		yield n1 + n2
		n1, n2 = n2, n1 + n2


if __name__ == '__main__':
	print(main(4000000))
