prompt = '''

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
from functools import reduce
from itertools import count
from math import sqrt
from typing import Iterable

from ..utilities import prime_factors


async def solve(logger):
    logger.debug(prompt)
    limit = 500
    for t in triangles(start=3):
        # p_factors = prime_factors(triangle)
        factors = prime_factors(t)
        factor_count = reduce(lambda x, y: x * y, (exp + 1 for prime, exp in factors))
        # all_factors = reduce(lambda x, y: x * y, [x[1] + 1 for x in p_factors])
        # logger.debug(f'{t} has {factor_count} factors')
        if factor_count > limit:
            return t


def triangles(start: int = 1) -> Iterable[int]:
    for x in count(start):
        yield int(x * (x + 1) / 2)
